import { z } from 'zod';

// Recipe document schema (issue #179). Validated on read in firebase-sync and on
// flow output in the parse CF (Phase 3). This is the single source of truth for
// the recipe shape: the recipe entity graph in packages/domain/src/recipe/entities
// aliases the inferred types below (issue #417), so entity and document can't drift.

// A plain numeric amount, e.g. "2", "0.5", "200".
export const SingleQuantitySchema = z.object({
  type: z.literal('single'),
  value: z.number(),
});

// A low–high amount, e.g. "2–3".
export const RangeQuantitySchema = z.object({
  type: z.literal('range'),
  min: z.number(),
  max: z.number(),
});

// A whole number plus an exact fraction, e.g. "1 ½" = { whole: 1, numerator: 1,
// denominator: 2 }; a bare "½" is whole 0. Stored as a fraction (not a decimal)
// so the original is preserved exactly. denominator is positive to stay a valid
// fraction.
export const MixedQuantitySchema = z.object({
  type: z.literal('mixed'),
  whole: z.number().int().nonnegative(),
  numerator: z.number().int().nonnegative(),
  denominator: z.number().int().positive(),
});

export const QuantitySchema = z.discriminatedUnion('type', [
  SingleQuantitySchema,
  RangeQuantitySchema,
  MixedQuantitySchema,
]);

export const ParsedIngredientSchema = z.object({
  quantity: QuantitySchema.nullable(),
  // Metric unit only. null for count/item-based ingredients (cloves, rashers, etc.)
  unit: z.enum(['g', 'ml']).nullable(),
  item: z.string(),
  preparation: z.array(z.string()),
  notes: z.string().nullable(),
  // Human-friendly display string for the original non-metric measure, e.g. "½ tsp"
  // or "1 cup". null when the source was already in g/ml or has no unit.
  // .default(null) so documents written before this field was added still parse.
  displayText: z.string().nullable().default(null),
});

export const IngredientSchema = z.object({
  id: z.string(),
  rawText: z.string(),
  parsed: ParsedIngredientSchema.nullable(),
  canonId: z.string().nullable(),
  matchState: z.enum(['pending', 'matched', 'failed']),
  isOptional: z.boolean(),
  firstUsedInStepId: z.string().nullable(),
});

export const IngredientGroupSchema = z.object({
  id: z.string(),
  name: z.string().nullable(),
  items: z.array(IngredientSchema),
});

export const StepTimerSchema = z.object({
  durationMinutes: z.number(),
  description: z.string().nullable(),
});

export const StepSchema = z.object({
  id: z.string(),
  text: z.string(),
  timer: StepTimerSchema.nullable(),
  note: z.string().nullable(),
});

export const RecipeMetadataSchema = z.object({
  servings: z.number().nullable(),
  totalTimeMinutes: z.number().nullable(),
  prepTimeMinutes: z.number().nullable(),
  cookTimeMinutes: z.number().nullable(),
  tags: z.array(z.string()),
});

export const RecipeSourceSchema = z.object({
  type: z.enum(['url', 'book', 'manual']),
  url: z.string().optional(),
  book: z
    .object({
      title: z.string(),
      author: z.string(),
      page: z.number(),
    })
    .optional(),
});

export const RecipeImageSchema = z.object({
  url: z.string(),
  // `ai` — the photoreal hero generated by the onRecipeWritten trigger (issue
  // #148 Tier-2); `upload` — a user-supplied photo (reserved seam, not produced
  // yet). The trigger only ever writes/overwrites an `ai` image and never
  // touches an `upload` one, so a manual photo is never clobbered.
  source: z.enum(['ai', 'upload']),
});

export const RecipeSchema = z.object({
  id: z.string(),
  schemaVersion: z.literal(1),
  title: z.string(),
  description: z.string().nullable(),
  ingredients: z.array(IngredientGroupSchema),
  steps: z.array(StepSchema),
  metadata: RecipeMetadataSchema,
  source: RecipeSourceSchema.nullable(),
  notes: z.string().nullable(),
  // The grocery item this recipe produces, if any ("buy or make", Phase 1). A
  // canon item id, or null when the recipe isn't linked to a grocery item.
  // `.default(null)` (NOT `.optional()`) so recipes written before this field
  // parse cleanly to `null` on read — back-compat on production data (#240) —
  // and every reader sees a concrete `string | null`, never `undefined`.
  producesCanonId: z.string().nullable().default(null),
  // The photoreal "arty" hero image (Tier-2, issue #148). `null` = none yet: the
  // onRecipeWritten trigger generates one from the title + description on create.
  // A non-null `{ url, source }` is rendered; the trigger skips it (already
  // generated, or a user upload). See the three transient control fields below.
  image: RecipeImageSchema.nullable(),
  // ─── Hero-image control fields (all optional + additive → back-compat on read;
  // documents written before Tier-2 lack them and stay valid) ──────────────────
  //
  // Transient one-shot steer for the next hero (re)generation. Written by the
  // regenerateRecipeImage callable alongside `image: null`; consumed and cleared
  // by the onRecipeWritten image branch. Mirrors CanonItem.iconHint.
  imageHint: z.string().optional(),
  // Regenerate nonce (epoch ms): the regenerateRecipeImage callable stamps this on
  // every request so the write always mutates the doc — even when `image` is
  // already null — which is what re-fires the onRecipeWritten image branch
  // (Firestore emits no write event for a no-op update). Mirrors iconRequestedAt.
  imageRequestedAt: z.number().optional(),
  // Opt-out: when true the trigger never auto-generates a hero and the UI hides
  // any existing one. "Hide" sets it true (a plain client write, no callable —
  // it needs no server authority); "Show" clears it; "Regenerate" clears it too.
  // Distinct from `image === null` (which means "generate one"). Mirrors the
  // CanonItem "hidden" thumbnail sentinel, but as its own boolean so
  // RecipeImageSchema stays a real image (url + source), never a sentinel.
  imageHidden: z.boolean().optional(),
  // Art-direction brief for the hero: a prose paragraph describing what the
  // plated dish looks like and how it reads in mood/season/cuisine, authored by
  // the describeRecipeScene flow from the WHOLE recipe (ingredients and steps
  // included) and consumed by the onRecipeWritten image branch, which persists it
  // alongside the image it produced. Present on the doc → used verbatim; absent →
  // authored on the next generation. `.optional()` (NOT `.default(null)` — that
  // idiom is for content fields like producesCanonId): this is a hero-image
  // control field like its neighbours above, and recipes written before it
  // existed simply lack it and must keep parsing (back-compat, #240).
  imageBrief: z.string().optional(),
  createdAt: z.string(),
  updatedAt: z.string(),
});

export type SingleQuantityDoc = z.infer<typeof SingleQuantitySchema>;
export type RangeQuantityDoc = z.infer<typeof RangeQuantitySchema>;
export type MixedQuantityDoc = z.infer<typeof MixedQuantitySchema>;
export type QuantityDoc = z.infer<typeof QuantitySchema>;
export type ParsedIngredientDoc = z.infer<typeof ParsedIngredientSchema>;
export type IngredientDoc = z.infer<typeof IngredientSchema>;
export type IngredientGroupDoc = z.infer<typeof IngredientGroupSchema>;
export type StepTimerDoc = z.infer<typeof StepTimerSchema>;
export type StepDoc = z.infer<typeof StepSchema>;
export type RecipeMetadataDoc = z.infer<typeof RecipeMetadataSchema>;
export type RecipeSourceDoc = z.infer<typeof RecipeSourceSchema>;
export type RecipeImageDoc = z.infer<typeof RecipeImageSchema>;
export type RecipeDoc = z.infer<typeof RecipeSchema>;
