import { z } from 'zod';

// Recipe document schema (issue #179). Validated on read in firebase-sync and on
// flow output in the parse CF (Phase 3). This is the single source of truth for
// the recipe shape: the recipe entity graph in packages/domain/src/recipe/entities
// aliases the inferred types below (issue #417), so entity and document can't drift.

// A plain numeric amount, e.g. "2", "0.5", "200".
export const SingleQuantitySchema = z.object({
  type: z.literal('single'),
  value: z.number(),
});

// A low–high amount, e.g. "2–3".
export const RangeQuantitySchema = z.object({
  type: z.literal('range'),
  min: z.number(),
  max: z.number(),
});

// A whole number plus an exact fraction, e.g. "1 ½" = { whole: 1, numerator: 1,
// denominator: 2 }; a bare "½" is whole 0. Stored as a fraction (not a decimal)
// so the original is preserved exactly. denominator is positive to stay a valid
// fraction.
export const MixedQuantitySchema = z.object({
  type: z.literal('mixed'),
  whole: z.number().int().nonnegative(),
  numerator: z.number().int().nonnegative(),
  denominator: z.number().int().positive(),
});

export const QuantitySchema = z.discriminatedUnion('type', [
  SingleQuantitySchema,
  RangeQuantitySchema,
  MixedQuantitySchema,
]);

export const ParsedIngredientSchema = z.object({
  quantity: QuantitySchema.nullable(),
  // Metric unit only. null for count/item-based ingredients (cloves, rashers, etc.)
  unit: z.enum(['g', 'ml']).nullable(),
  item: z.string(),
  preparation: z.array(z.string()),
  notes: z.string().nullable(),
  // Human-friendly display string for the original non-metric measure, e.g. "½ tsp"
  // or "1 cup". null when the source was already in g/ml or has no unit.
  // .default(null) so documents written before this field was added still parse.
  displayText: z.string().nullable().default(null),
});

export const IngredientSchema = z.object({
  id: z.string(),
  rawText: z.string(),
  parsed: ParsedIngredientSchema.nullable(),
  canonId: z.string().nullable(),
  matchState: z.enum(['pending', 'matched', 'failed']),
  isOptional: z.boolean(),
  firstUsedInStepId: z.string().nullable(),
});

export const IngredientGroupSchema = z.object({
  id: z.string(),
  name: z.string().nullable(),
  items: z.array(IngredientSchema),
});

export const StepTimerSchema = z.object({
  durationMinutes: z.number(),
  description: z.string().nullable(),
});

export const StepSchema = z.object({
  id: z.string(),
  text: z.string(),
  timer: StepTimerSchema.nullable(),
  note: z.string().nullable(),
});

export const RecipeMetadataSchema = z.object({
  servings: z.number().nullable(),
  totalTimeMinutes: z.number().nullable(),
  prepTimeMinutes: z.number().nullable(),
  cookTimeMinutes: z.number().nullable(),
  tags: z.array(z.string()),
});

export const RecipeSourceSchema = z.object({
  type: z.enum(['url', 'book', 'manual']),
  url: z.string().optional(),
  // Book provenance, filled from what a photographed page actually SHOWS (issue
  // #649): a running head, an author's name, a printed page number. Any of the
  // three can be absent from the crop the user took, and the model is told to
  // omit rather than invent — so each part is individually optional and the whole
  // object is dropped when nothing was legible.
  //
  // Relaxing these from required to optional is a widening: every document that
  // parsed before still parses, and nothing in the codebase has ever written a
  // `type: 'book'` source, so no production document is affected and no migration
  // is needed (salt-architecture.md §1.1).
  book: z
    .object({
      title: z.string().optional(),
      author: z.string().optional(),
      page: z.number().optional(),
    })
    .optional(),
});

export const RecipeImageSchema = z.object({
  url: z.string(),
  // `ai` — the photoreal hero generated by the onRecipeWritten trigger (issue
  // #148 Tier-2); `upload` — a user-supplied photo (reserved seam, not produced
  // yet). The trigger only ever writes/overwrites an `ai` image and never
  // touches an `upload` one, so a manual photo is never clobbered.
  source: z.enum(['ai', 'upload']),
});

// What kind of entry this is (issue #637). The `recipes` collection holds more
// than recipes: an `outing` is a takeaway / picnic / meal out — it fills a
// planner slot but has no ingredients and no method; a `cocktail` has both but
// is never a dinner; a `placeholder` (issue #652) is neither — it is a stock
// photograph of "a good dinner, no particular dish", attached to a planner day
// that was planned in a sentence so that night gets a card like any other.
// NOTHING outside packages/domain branches on this value — behaviour comes from
// the pure capability predicates in `recipe/queries/capabilities.ts`, so the
// fourth kind was, as promised, a one-file change there.
//
// Adding a member here is back-compatible on read by construction: `kind` carries
// `.default('recipe')` below, so every document already in production parses
// unchanged (salt-architecture.md §1.1 — no migration).
export const RecipeKindSchema = z.enum(['recipe', 'outing', 'cocktail', 'placeholder']);

export const RecipeSchema = z.object({
  id: z.string(),
  schemaVersion: z.literal(1),
  // `.default('recipe')` (NOT `.optional()`) is load-bearing, not stylistic: the
  // realtime subscription skips documents that fail validation, so a required
  // `kind` would make every recipe already in production (#240) silently vanish
  // from the list. Defaulted, they read back as exactly what they are — recipes.
  kind: RecipeKindSchema.default('recipe'),
  title: z.string(),
  description: z.string().nullable(),
  ingredients: z.array(IngredientGroupSchema),
  steps: z.array(StepSchema),
  metadata: RecipeMetadataSchema,
  source: RecipeSourceSchema.nullable(),
  notes: z.string().nullable(),
  // The grocery item this recipe produces, if any ("buy or make", Phase 1). A
  // canon item id, or null when the recipe isn't linked to a grocery item.
  // `.default(null)` (NOT `.optional()`) so recipes written before this field
  // parse cleanly to `null` on read — back-compat on production data (#240) —
  // and every reader sees a concrete `string | null`, never `undefined`.
  producesCanonId: z.string().nullable().default(null),
  // Review state for AI-authored recipes (issue #616). Set by the URL-import
  // callable, which persists the extracted recipe itself so a share-sheet import
  // (#589) survives the PWA being killed mid-extraction. Same used-but-flagged
  // semantics as CanonItem/ProductForm `needs_approval`: the recipe is fully live
  // — cookable, plannable, searchable — the flag ONLY records that no human has
  // read it yet. It is never a gate on use, and it is never filtered out.
  // Cleared by an editor save (that save IS the review) or by tapping the chip on
  // the recipe. `.optional()` (mirroring ProductFormSchema) so the production
  // recipes collection parses unchanged on read — absent means reviewed (#240).
  needs_approval: z.boolean().optional(),
  // The dishes this entry is built from (issue #752). A Sunday roast is one
  // recipe document that points at roast chicken, roast potatoes and onion gravy;
  // "is this a meal?" is DERIVED from this array being non-empty, never declared,
  // so there is no fifth `kind` and no second collection. The recipe keeps its
  // own ingredients, steps and notes — nothing aggregates and nothing recurses:
  // components resolve exactly one level deep for display, which is what makes a
  // reference cycle inert and the whole feature O(1). A dangling id (component
  // deleted elsewhere) is skipped silently on read; there is no cascade and no
  // tombstone. `.default([])` (NOT `.optional()`) for both reasons that made
  // `producesCanonId` two fields above take the same shape: the realtime
  // subscription skips documents that fail validation, so a required field would
  // make every recipe already in production (#240) silently vanish from the list,
  // and defaulted, every reader sees a concrete `string[]` rather than `undefined`.
  componentRecipeIds: z.array(z.string()).default([]),
  // The photoreal "arty" hero image (Tier-2, issue #148). `null` = none yet: the
  // onRecipeWritten trigger generates one from the title + description on create.
  // A non-null `{ url, source }` is rendered; the trigger skips it (already
  // generated, or a user upload). See the three transient control fields below.
  image: RecipeImageSchema.nullable(),
  // ─── Hero-image control fields (all optional + additive → back-compat on read;
  // documents written before Tier-2 lack them and stay valid) ──────────────────
  //
  // Transient one-shot steer for the next hero (re)generation. Written by the
  // regenerateRecipeImage callable alongside `image: null`; consumed and cleared
  // by the onRecipeWritten image branch. Mirrors CanonItem.iconHint.
  imageHint: z.string().optional(),
  // Regenerate nonce (epoch ms): the regenerateRecipeImage callable stamps this on
  // every request so the write always mutates the doc — even when `image` is
  // already null — which is what re-fires the onRecipeWritten image branch
  // (Firestore emits no write event for a no-op update). Mirrors iconRequestedAt.
  imageRequestedAt: z.number().optional(),
  // RETIRED and inert: kept on the schema only so production documents that still
  // carry it parse on read (#240). It has no readers anywhere — onRecipeWritten
  // stopped honouring it (auto-generation now runs regardless), and as of #648 no
  // web-pwa site reads it either: hero visibility is purely "does an image URL
  // exist". Its only remaining mention is the regenerateRecipeImage callable
  // deleting it, which is cleanup of legacy data, not a read. It formerly meant
  // "never auto-generate a hero, and hide any existing one" — do not resurrect
  // that behaviour without reinstating readers on both sides.
  imageHidden: z.boolean().optional(),
  // Art-direction brief for the hero: a prose paragraph describing what the
  // plated dish looks like and how it reads in mood/season/cuisine, authored by
  // the describeRecipeScene flow from the WHOLE recipe (ingredients and steps
  // included) and consumed by the onRecipeWritten image branch, which persists it
  // alongside the image it produced. Present on the doc → used verbatim; absent →
  // authored on the next generation. `.optional()` (NOT `.default(null)` — that
  // idiom is for content fields like producesCanonId): this is a hero-image
  // control field like its neighbours above, and recipes written before it
  // existed simply lack it and must keep parsing (back-compat, #240).
  imageBrief: z.string().optional(),
  createdAt: z.string(),
  updatedAt: z.string(),
});

export type SingleQuantityDoc = z.infer<typeof SingleQuantitySchema>;
export type RangeQuantityDoc = z.infer<typeof RangeQuantitySchema>;
export type MixedQuantityDoc = z.infer<typeof MixedQuantitySchema>;
export type QuantityDoc = z.infer<typeof QuantitySchema>;
export type ParsedIngredientDoc = z.infer<typeof ParsedIngredientSchema>;
export type IngredientDoc = z.infer<typeof IngredientSchema>;
export type IngredientGroupDoc = z.infer<typeof IngredientGroupSchema>;
export type StepTimerDoc = z.infer<typeof StepTimerSchema>;
export type StepDoc = z.infer<typeof StepSchema>;
export type RecipeMetadataDoc = z.infer<typeof RecipeMetadataSchema>;
export type RecipeSourceDoc = z.infer<typeof RecipeSourceSchema>;
export type RecipeImageDoc = z.infer<typeof RecipeImageSchema>;
export type RecipeKindDoc = z.infer<typeof RecipeKindSchema>;
export type RecipeDoc = z.infer<typeof RecipeSchema>;
