// Service-worker registration + auto-update / deferred-reload flow (issue #141).
//
// The service worker itself is generated by vite-plugin-pwa (Workbox) and is the
// ONLY place the Cache API is used, and only for the app shell/assets — the
// deliberate, contained exception to CLAUDE.md hard rule #3. This module talks
// only to navigator.serviceWorker; it never touches `caches`, localStorage, or
// any other browser storage directly.
//
// Update strategy (decided in #141): the generated SW ships with skipWaiting +
// clientsClaim, so a newly-installed SW takes control immediately. We do NOT
// reload the page the instant that happens — that would be a disruptive
// mid-interaction reload. Instead we mark the update pending and reload at the
// next *safe* moment: a route change (svelte-spa-router drives the URL hash) or
// the user returning focus to the tab. Reload is data-safe because all real
// state lives in Firestore persistentLocalCache; at worst a transient, untyped
// form field is lost, hence deferring rather than blocking.
//
// A long-open SPA never re-fetches sw.js on its own (route changes don't trigger
// it), so we explicitly poll registration.update() on an interval and on
// refocus — without this a release never reaches an already-open client.

const SW_URL = '/sw.js';

// ~20 min sits inside the 15–30 min window from #141: frequent enough that an
// open client picks up a release promptly, infrequent enough to be negligible.
const UPDATE_INTERVAL_MS = 20 * 60 * 1000;

export function registerServiceWorker(): void {
  // No SW in dev (HMR + the e2e Vite dev server). Only the production build
  // emits and registers one.
  if (import.meta.env.DEV) return;
  if (typeof navigator === 'undefined' || !('serviceWorker' in navigator)) return;

  window.addEventListener('load', () => {
    navigator.serviceWorker
      // updateViaCache: 'none' so the browser always revalidates sw.js against
      // the network on update checks. Paired with the Firebase Hosting
      // Cache-Control: no-cache header on /sw.js, this closes the stale-SW trap.
      .register(SW_URL, { updateViaCache: 'none' })
      .then(setupUpdateFlow)
      .catch(() => {
        // Registration failure is non-fatal: the app still runs online, it just
        // isn't installable/offline-capable until the next successful load.
      });
  });
}

function setupUpdateFlow(registration: ServiceWorkerRegistration): void {
  let updatePending = false;
  let reloading = false;

  const reloadIfSafe = (): void => {
    if (!updatePending || reloading) return;
    reloading = true;
    window.location.reload();
  };

  // A new SW has installed and (because skipWaiting + clientsClaim) taken
  // control. Only flag it here — do NOT reload now; that is the disruptive
  // mid-interaction reload #141 forbids. The reload happens on the next safe
  // event below.
  navigator.serviceWorker.addEventListener('controllerchange', () => {
    updatePending = true;
  });

  // Safe reload moments.
  // svelte-spa-router navigates via the URL hash, so a route change surfaces as
  // a hashchange — reload there so the new route loads fresh (correctly-hashed)
  // chunks rather than 404-ing against the old build.
  window.addEventListener('hashchange', reloadIfSafe);
  // Returning focus to the tab: first kick an update check (an open background
  // tab may have missed the interval), then reload if an update has landed.
  window.addEventListener('focus', () => {
    void registration.update();
    reloadIfSafe();
  });
  document.addEventListener('visibilitychange', () => {
    if (document.visibilityState !== 'visible') return;
    void registration.update();
    reloadIfSafe();
  });

  // Timely update detection for a long-open client.
  setInterval(() => {
    void registration.update();
  }, UPDATE_INTERVAL_MS);
}
